//! Emit the frontend's TS type surface (`frontend/src/generated/bindings.ts`) from
//! the same `specta::Type` derives the daemon serializes with — one source, no
//! hand-written type drift. The registered roots pull in every transitively
//! referenced type (profiles, settings, intents, wire frames), which is exactly
//! the set the UI imports.

use kasumi_backend::{Command, Response};
use kasumi_core::contract::{
    AssetsUpdatedEvent, Capabilities, LogTarget, PushFrame, ServiceStatus, TestKind, WsInfo,
};
use kasumi_core::mutate::MutationIntent;
use kasumi_core::profile::Protocol;
use kasumi_core::state::AppState;

use crate::cast::cast_bigints_to_number;

/// Every wire root the bindings must cover. `register` walks references, so the
/// full type graph lands in the file. `Protocol` is registered explicitly: the
/// profile union carries it per-variant but the standalone enum is part of the
/// UI's surface (protocol selects, per-protocol maps).
pub fn wire_types() -> specta::Types {
    let types = specta::Types::default()
        .register::<Command>()
        .register::<Response>()
        .register::<ServiceStatus>()
        .register::<PushFrame>()
        .register::<AssetsUpdatedEvent>()
        .register::<Capabilities>()
        .register::<WsInfo>()
        .register::<LogTarget>()
        .register::<TestKind>()
        .register::<AppState>()
        .register::<Protocol>()
        .register::<MutationIntent>();
    cast_bigints_to_number(types)
}

/// Render the TS module.
pub fn render() -> String {
    // `PhasesFormat` keeps deserialize-only widening (serde `alias`/`default`/
    // `skip_serializing_if`) faithful by splitting asymmetric types into
    // `_Serialize`/`_Deserialize` pairs.
    specta_typescript::Typescript::new()
        .header("// Generated by `cargo run -p kasumi-codegen`. Do not edit it manually.\n")
        .export(&wire_types(), specta_serde::PhasesFormat)
        .expect("export typescript bindings")
}
